---
name: CI
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check
        run: go test -v ./...
      - name: Build
        run: go build -v ./...
...
